services: docker

script:
  - echo "no test"

deploy:
  provider: script
  on:
    tags: true
  script:
    - echo "hello"
    - docker login -u zhaoqin -p $PASSWORD
    - docker build -t zhaoqin/fluentd:latest .
    - docker push zhaoqin/fluentd:latest
    - docker logout
