language: minimal
services: docker

script:
  - echo "no test"
  - export NAME=zhaoqin

deploy:
  provider: script
  script:
    - echo "line 1"
    - echo "line 2"
    - ./publish_image.sh
  on:
    tags: true
